version: '2'
services:

  web:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: andrdru/php-fpm
    volumes:
      - ./src:/src
      - ./php/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/opt/setup

