#!/bin/sh

if [ -z "$1" ]; then
  echo "Please specify a directory to use"
  exit 1
fi

if [ -e $1 ]; then
  echo "$1 already exists"
  exit 1
fi

mkdir -p "$1/config"
if [ $? -ne 0 ]; then
  echo "Failed to create directory."
  exit 1
fi

cd "$1"

cat > config/site.conf <<EOS
server {
  listen 80;
  index index.php index.html;
  server_name localhost;
  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  root /src;

  sendfile    on;
  client_max_body_size 32m;

  location ~ \.php\$ {
    try_files \$uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)\$;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    fastcgi_param PATH_INFO \$fastcgi_path_info;
    # you can proxy_set_header X-Real-Ip \$remote_addr on reverse proxy to send real ip into container
    #fastcgi_param REMOTE_ADDR \$http_x_real_ip;
  }

  location ~ \.p8\$ {
    deny all;
  }
}
EOS

cat > config/conf.ini <<EOS
file_uploads = On
memory_limit = 512M
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 500
EOS

cat > docker-compose.yml <<EOS
version: '2'
services:

    web:
        image: nginx:latest
        restart: always
        container_name: web_apns
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        image: andrdru/php-fpm
        container_name: php_apns
        restart: always
        volumes:
            - ./src:/src
            - ./config/conf.ini:/usr/local/etc/php/conf.d/conf.ini
        networks:
            - code-network

    db:
        image: postgres:latest
        restart: always
        container_name: db_apns
        ports:
            - "5432:5432"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge

EOS

docker-compose up -d
